export const phrases = [
    "DOT THE I'S AND CROSS THE T'S",
    "Cricling back",
    "low hanging fruit",
    "boots on the ground",
    "win-win",
    "think outside the box!",
    "at the end of the day",
    "lets touch base",
    "moving forward",
    "giving it 110%",
    "Data-driven",
    "on the radar",
    "what are your thoughts",
    "pain point",
    "synergy",
    "if i can make a suggestion",
    "put on the record",
    "hit the ground running",
    "value-added",
    "high performing",
    "on the same page",
    "bang for your buck",
    "no brainer",
    "pivot",
];
